format = """
$all\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

[package]
disabled = true

[aws]
symbol = " "
[aws.region_aliases]
eu-central-1 = "eu-ct-1"

[git_branch]
symbol = " "
[git_commit]
tag_disabled = false
[git_metrics]
disabled = false

[golang]
symbol = " "

