theme = "githubsy"

[editor]
line-number = "relative"
mouse = true
color-modes = true
idle-timeout = 100
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'<' = '>'

[editor.soft-wrap]
enable = true

[editor.terminal]
command = "kitty"
args = ["-c"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"i" = ["insert_mode", "collapse_selection"]
"a" = ["append_mode", "collapse_selection"]
"A-k" = "move_line_up"
"∞" = "flip_selections" # Output of alt+; on Mac (DE Layout)
"…" = "flip_selections" # Output of alt+; on Mac (US Layout)
# "," = "collapse_selection"
# ";" = "keep_primary_selection"
"C-l" = "goto_next_buffer"
"C-h" = "goto_previous_buffer"
"X" = ["ensure_selections_forward", "flip_selections", "extend_line_up", "extend_to_line_bounds"]
"c" = ["trim_selections", "change_selection"]
"C-k" = ["insert_mode", "kill_to_line_end"]

[keys.insert]
"C-j" = "normal_mode"
"C-o" = ["add_newline_below", "move_line_down"]
"C-p" = "move_line_up"
"C-n" = "move_line_down"
"ƒ" = "move_next_word_start"
"∫" = "move_prev_word_end"
"C-f" = "move_char_right"
"C-b" = "move_char_left"

[keys.select]
"C-j" = ["normal_mode", "collapse_selection"]
# "∞" = "flip_selections"

[keys.normal.space]
F = "file_picker"
f = "file_picker_in_current_directory"
w = ":w"
q = ":q"
c = ":bc"
x = ":x"
t = ":sh kitty @ launch --no-response --type os-window --cwd current --title 'cargo-test' && kitty @ send-text --match 'title:^cargo-test' 'cargo test\\n'"

[keys.normal."C-backspace"]
c = ":config-open"
o = ":config-open"
r = ":config-reload"
l = ":o ~/.config/helix/languages.toml"
