console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  base = '#1e1e2e'
  blue = '#89b4fa'
  crust = '#11111b'
  flamingo = '#f2cdcd'
  green = '#a6e3a1'
  lavender = '#b4befe'
  mantle = '#181825'
  maroon = '#eba0ac'
  mauve = '#cba6f7'
  overlay0 = '#6c7086'
  overlay1 = '#7f849c'
  overlay2 = '#9399b2'
  peach = '#fab387'
  pink = '#f5c2e7'
  red = '#f38ba8'
  rosewater = '#f5e0dc'
  sapphire = '#74c7ec'
  sky = '#89dceb'
  subtext0 = '#a6adc8'
  subtext1 = '#bac2de'
  surface0 = '#313244'
  surface1 = '#45475a'
  surface2 = '#585b70'
  teal = '#94e2d5'
  text = '#cdd6f4'
  yellow = '#f9e2af'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'blue'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '<b>{{ .Path }}</b>'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '{{ if .Env.DEVBOX_SHELL_ENABLED }}<p:purple><b> [db]</b></p:purple>{{ end }}'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<p:peach>  {{ .Full }}</p:peach>'
    type = 'rust'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<p:green>  {{ .Full }}</p:green>'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<p:sky> ‭ﳑ {{ .Full }}</p:sky>'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<p:blue>  {{ .Full }}</p:blue>'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <p:mauve>{{ .HEAD }}</p:mauve><p:peach>{{ if .Working.Changed }} {{ .Working.String }}{{ end }}</p:peach><p:yellow>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}</p:yellow>'
    background = 'transparent'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = ' '
      branch_identical_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
