# Variant "Original":
# "type" = "pl-variable"
# "type.builtin" = "pl-constant"
# "variable.other.member" = "pl-string"

# Variant Set 1


# Syntax highlighting
# -------------------
# Variant "Blue":
"type" = "pl-constant"
"type.builtin" = "pl-string"
"variable.other.member" = "pl-type"

"variable" = "pl-fg-default"
"variable.parameter" = { fg = "mistypurple", modifiers = ["italic"] }
"variable.builtin" = "jazzyorange"

"constant" = "pillsypurple"
"constant.builtin" = "mistyblue"
"constant.numeric" = "mistyblue"
"constant.character" = "trueblue"
# "constant.character.escape" = "pink"

"constructor" = "pl-variable"

"function" = { fg = "pillsypurple"  }
"function.builtin" = "pleasingpurple"
"function.macro" = "pl-entity"

# "string" = "mistyblue"
"string.regexp" = "pillsypurple"
"string.special" = "trueblue"

"comment" = { fg = "pl-comment", modifiers = ["italic"] }

"label" = "jazzyorange" # used for lifetimes

"punctuation" = "normiewhitey"
"punctuation.delimiter" = "mistypurple"
"punctuation.special" = "lizardgreen"

"keyword" = { fg = "pl-keyword" }
# "keyword.function" = "pleasingpurple"
"keyword.control" = { fg = "rustyred", modifiers = ["italic"] }
"keyword.storage.modifier" = { fg = "eminentred", modifiers = ["italic"] }

"operator" = "pl-string"

"tag" = "pl-entity-tag"

"namespace" = { fg = "pl-fg-default", modifiers = ["italic"] }

# "special" = "blue" # fuzzy highlight

"markup" = "mistyblue"
"markup.heading.marker" = { fg = "jazzyorange", modifiers = ["bold"] }
"markup.heading.1" = "rustyred"
"markup.heading.2" = "poppinblue"
"markup.heading.3" = "mistygreen"
"markup.heading.4" = "mistyblue"
"markup.heading.5" = "mistypurple"
"markup.heading.6" = "normiewhitey"
"markup.list" = "jazzyorange"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "mistygreen", modifiers = ["italic", "underlined"] }
"markup.link.text" = "mistyblue"
"markup.raw" = "mistyblue"

"diff.plus" = "acidgreen"
"diff.minus" = "redalert"
"diff.delta" = "trueblue"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "pl-background" }

"ui.linenr" = { fg = "steelgray" }
"ui.linenr.selected" = { fg = "pillsypurple" }

"ui.statusline" = { fg = "text", bg = "base" }
# "ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.normal" = { fg = "almostblack", bg = "purplegray", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "almostblack", bg = "lizardgreen", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "almostblack", bg = "jazzyorange", modifiers = ["bold"] }

"ui.text" = "trueblue"
"ui.text.focus" = { fg = "jazzyorange", bg = "almostnotgray", modifiers = ["bold"] }

"ui.popup" = { fg = "trueblue", bg = "almostnotgray" }
"ui.window" = { fg = "bluegray" }
"ui.help" = { fg = "text", bg = "almostnotgray" }

"ui.menu" = { fg = "trueblue", bg = "almostnotgray" }
"ui.menu.selected" = { fg = "jazzyorange", bg = "almostnotgray", modifiers = ["bold"] }

"ui.bufferline" = { fg = "trueblue", bg = "pl-background" }
"ui.bufferline.active" = { fg = "pl-variable", modifiers = [
    "bold",
    "italic",
] }

"ui.virtual" = "almostnotgray"
# "ui.virtual.ruler" = { bg = "surface0" }
# "ui.virtual.indent-guide" = "surface0"
"ui.virtual.inlay-hint" = "scale.gray.4"

"ui.selection" = { bg = "almostnotgray" }

"ui.cursor" = { fg = "almostnotgray", bg = "poppinblue" } # Secondary cursor.
"ui.cursor.primary" = { fg = "almostnotgray", bg = "pl-variable" }
"ui.cursor.match" = { fg = "almostnotgray", bg = "mistyblue", modifiers = ["bold"] }

# "ui.cursorline.primary" = { bg = "cursorline" }

# "ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "redalert", style = "curl" } }
"diagnostic.warning" = { underline = { color = "wheetywarning", style = "curl" } }
"diagnostic.info" = { underline = { color = "lizardgreen", style = "curl" } }
"diagnostic.hint" = { underline = { color = "mistyblue", style = "curl" } }

error = "redalert"
warning = "wheetywarning"
info = "lizardgreen"
hint = "mistyblue"

[palette]
allblack = "#000000"
almostblack = "#121212"
almostnotgray = "#303030"
steelgray = "#8787af"
normiewhitey = "#d7d7d7"
purplegray = "#8787d7"
bluegray = "#5f87af"
greengray = "#87afaf"
redalert = "#ff4a2c"
wheetywarning = "#ffffaf"
eminentred = "#d75f5f"
# rustyred = "#ff875f"
rustyred = "#ff7b72"
# jazzyorange = "#ffaf5f"
jazzyorange = "#ffa657"
rosiebrown = "#af8787"
pleasingpurple = "#af87ff"
pillsypurple = "#d7afff"
mistypurple = "#d7d7ff"
basicblue = "#005fd7"
candymethblue = "#5fafff"
trueblue = "#87afff"
poppinblue = "#87d7ff"
mistyblue = "#afd7ff"
powderblue = "#cce6ff"
acidgreen = "#87ff00"
lizardgreen = "#87d787"
mistygreen = "#d7ffff"

text =  "#8787d7" # purplegray
base = "#161624"

pl-background = "#0d1117"
pl-fg-default = "#e4e8ec" # mistypurple
pl-fg-muted = "#7a8490"

# ++++ SET 1 (see Figma)
# trueblue = "#2884C0" # blue.1
# candymethblue = "#5CAADC" # blue.2
# mistyblue = "#B2DCF8" # blue.3
# jazzyorange = "#FFA028" # orange.1
# rustyred = "#FF5F28" # red.1
# pleasingpurple = "#6A70E2" # purple.1
# pillsypurple = "#B9BCF9" # purple.2
# lizzardgreen = "#56E29F"

# acidgreen = "#20CA78"
# redalert = "#D83700" # red.2
# wheetywarning = "#FFD662"
# ++++

pl-variable = "#ffa657" # aka jazzyorange
pl-keyword = "#ff7b72" # aka rustyred ORANGE
pl-string = "#a5d6ff"
pl-comment = "#8b949e"
pl-constant = "#79c0ff" # aka member, BLUE
pl-entity = "#d2a8ff" # aka function
pl-entity-tag = "#7ee787"
pl-type = "#c9d1d9" # e.g. -> Self, T

base_blue = "#79c0ff" # aka member, BLUE
base_purple = "#d7afff" # PURPLE
base_orange = "#ffa657" # ORANGE
base_red = "#ff7b72" # aka rustyred ORANGE

# TODO: Create shades for each color.

# Colors from github_dark theme:
# https://github.com/helix-editor/helix/pull/5353/files
# "accent.emphasis" = "#1f6feb"
# "accent.fg" = "#58a6ff"
# "accent.muted" = "#388bfd66"
# "accent.subtle" = "#388bfd26"
# "attention.emphasis" = "#9e6a03"
# "attention.fg" = "#d29922"
# "attention.muted" = "#bb800966"
# "attention.subtle" = "#bb800926"
# "border.default" = "#30363d"
# "border.muted" = "#21262d"
# "border.subtle" = "#f0f6fc1a"
# "canvas.default" = "#0d1117"
# "canvas.inset" = "#010409"
# "canvas.overlay" = "#161b22"
# "canvas.subtle" = "#161b22"
# "closed.emphasis" = "#da3633"
# "closed.fg" = "#f85149"
# "closed.muted" = "#f8514966"
# "closed.subtle" = "#f8514926"
# "danger.emphasis" = "#da3633"
# "danger.fg" = "#f85149"
# "danger.muted" = "#f8514966"
# "danger.subtle" = "#f8514926"
# "done.emphasis" = "#8957e5"
# "done.fg" = "#a371f7"
# "done.muted" = "#a371f766"
# "done.subtle" = "#a371f726"
# "fg.default" = "#c9d1d9"
# "fg.muted" = "#8b949e"
# "fg.onEmphasis" = "#ffffff"
# "fg.subtle" = "#6e7681"
# "neutral.emphasis" = "#6e7681"
# "neutral.emphasisPlus" = "#6e7681"
# "neutral.muted" = "#6e768166"
# "neutral.subtle" = "#6e76811a"
# "open.emphasis" = "#238636"
# "open.fg" = "#3fb950"
# "open.muted" = "#2ea04366"
# "open.subtle" = "#2ea04326"
# "scale.black" = "#010409"
# "scale.blue.0" = "#cae8ff"
# "scale.blue.1" = "#a5d6ff"
# "scale.blue.2" = "#79c0ff"
# "scale.blue.3" = "#58a6ff"
# "scale.blue.4" = "#388bfd"
# "scale.blue.5" = "#1f6feb"
# "scale.blue.6" = "#1158c7"
# "scale.blue.7" = "#0d419d"
# "scale.blue.8" = "#0c2d6b"
# "scale.blue.9" = "#051d4d"
# "scale.coral.0" = "#ffddd2"
# "scale.coral.1" = "#ffc2b2"
# "scale.coral.2" = "#ffa28b"
# "scale.coral.3" = "#f78166"
# "scale.coral.4" = "#ea6045"
# "scale.coral.5" = "#cf462d"
# "scale.coral.6" = "#ac3220"
# "scale.coral.7" = "#872012"
# "scale.coral.8" = "#640d04"
# "scale.coral.9" = "#460701"
"scale.gray.0" = "#f0f6fc"
"scale.gray.1" = "#c9d1d9"
"scale.gray.2" = "#b1bac4"
"scale.gray.3" = "#8b949e"
"scale.gray.4" = "#6e7681"
"scale.gray.5" = "#484f58"
"scale.gray.6" = "#30363d"
"scale.gray.7" = "#21262d"
"scale.gray.8" = "#161b22"
"scale.gray.9" = "#0d1117"
# "scale.green.0" = "#aff5b4"
# "scale.green.1" = "#7ee787"
# "scale.green.2" = "#56d364"
# "scale.green.3" = "#3fb950"
# "scale.green.4" = "#2ea043"
# "scale.green.5" = "#238636"
# "scale.green.6" = "#196c2e"
# "scale.green.7" = "#0f5323"
# "scale.green.8" = "#033a16"
# "scale.green.9" = "#04260f"
# "scale.orange.0" = "#ffdfb6"
# "scale.orange.1" = "#ffc680"
# "scale.orange.2" = "#ffa657"
# "scale.orange.3" = "#f0883e"
# "scale.orange.4" = "#db6d28"
# "scale.orange.5" = "#bd561d"
# "scale.orange.6" = "#9b4215"
# "scale.orange.7" = "#762d0a"
# "scale.orange.8" = "#5a1e02"
# "scale.orange.9" = "#3d1300"
# "scale.pink.0" = "#ffdaec"
# "scale.pink.1" = "#ffbedd"
# "scale.pink.2" = "#ff9bce"
# "scale.pink.3" = "#f778ba"
# "scale.pink.4" = "#db61a2"
# "scale.pink.5" = "#bf4b8a"
# "scale.pink.6" = "#9e3670"
# "scale.pink.7" = "#7d2457"
# "scale.pink.8" = "#5e103e"
# "scale.pink.9" = "#42062a"
# "scale.purple.0" = "#eddeff"
# "scale.purple.1" = "#e2c5ff"
# "scale.purple.2" = "#d2a8ff"
# "scale.purple.3" = "#bc8cff"
# "scale.purple.4" = "#a371f7"
# "scale.purple.5" = "#8957e5"
# "scale.purple.6" = "#6e40c9"
# "scale.purple.7" = "#553098"
# "scale.purple.8" = "#3c1e70"
# "scale.purple.9" = "#271052"
# "scale.red.0" = "#ffdcd7"
# "scale.red.1" = "#ffc1ba"
# "scale.red.2" = "#ffa198"
# "scale.red.3" = "#ff7b72"
# "scale.red.4" = "#f85149"
# "scale.red.5" = "#da3633"
# "scale.red.6" = "#b62324"
# "scale.red.7" = "#8e1519"
# "scale.red.8" = "#67060c"
# "scale.red.9" = "#490202"
# "scale.white" = "#ffffff"
# "scale.yellow.0" = "#f8e3a1"
# "scale.yellow.1" = "#f2cc60"
# "scale.yellow.2" = "#e3b341"
# "scale.yellow.3" = "#d29922"
# "scale.yellow.4" = "#bb8009"
# "scale.yellow.5" = "#9e6a03"
# "scale.yellow.6" = "#845306"
# "scale.yellow.7" = "#693e00"
# "scale.yellow.8" = "#4b2900"
# "scale.yellow.9" = "#341a00"
# "severe.emphasis" = "#bd561d"
# "severe.fg" = "#db6d28"
# "severe.muted" = "#db6d2866"
# "severe.subtle" = "#db6d2826"
# "sponsors.emphasis" = "#bf4b8a"
# "sponsors.fg" = "#db61a2"
# "sponsors.muted" = "#db61a266"
# "sponsors.subtle" = "#db61a226"
# "success.emphasis" = "#238636"
# "success.fg" = "#3fb950"
# "success.muted" = "#2ea04366"
# "success.subtle" = "#2ea04326"
