# ---
# tabs:
#   - direction: Vertical
#     parts:
#       - direction: Horizontal
#         parts:
#           - direction: Vertical
#           - direction: Vertical
#       - direction: Horizontal
---
session:
  name: "dirty-default"
  attach: true
template:
  direction: Horizontal
  parts:
  - direction: Vertical  # part 1
    borderless: true
    split_size:
      Fixed: 1
    run:
      plugin:
        location: "zellij:tab-bar"
  - direction: Vertical
    body: true
  - direction: Vertical # part 3
    borderless: true
    split_size:
      Fixed: 2
    run:
      plugin:
        location: "zellij:status-bar"

tabs:
  - name: "tty"
  - name: "prx"
    direction: Vertical
    run:
      command: { cmd: zsh, args: ["-c", "cd ~/prx && zsh"] }
# ---
# template:
#   direction: Horizontal
#   parts:
#     - direction: Vertical  # part 1
#       borderless: true
#       split_size:
#         Fixed: 1
#       run:
#         plugin:
#           location: "zellij:tab-bar"
#     - direction: Vertical # part 2
#       body: true
#     - direction: Vertical # part 3
#       borderless: true
#       split_size:
#         Fixed: 2
#       run:
#         plugin:
#           location: "zellij:status-bar"
